version: '3.9'

networks:
  dev_network:

services:

  db:
    build: db
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    networks:
      dev_network:
        aliases:
          - db_main

  app:
    depends_on:
      - db
    build:
      context: .
    env_file:
      - ./.env
    ports:
      - "5000:5000"
    networks:
      dev_network:
        aliases:
          - app
    volumes:
      - ./:/app
